version: '3.8'

services:
  l0:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nats-str
    environment:
      - DB_PASSWORD=0000

  db:
    restart: always
    build: ./pkg/sql
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"
  nats-str:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  db: